# Generated by Django 3.2.15 on 2022-10-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('user_name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('bids_left', models.IntegerField(default=0, verbose_name='Bids Left')),
                ('otp', models.CharField(default='000000', max_length=6)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_is_replied', models.BooleanField(default=0, verbose_name='Notification_is_replied')),
                ('notification_is_new_bid', models.BooleanField(default=0, verbose_name='Notification_is_new_bid')),
                ('notification_is_sound', models.BooleanField(default=0, verbose_name='notifications_is_sound')),
                ('email_is_auction_end', models.BooleanField(default=0, verbose_name='Email_is_auction_end')),
                ('email_is_new_bid', models.BooleanField(default=0, verbose_name='Email_is_new_bid')),
                ('email_is_new_comment', models.BooleanField(default=0, verbose_name='Email_is_new_comment')),
                ('email_is_out_bid', models.BooleanField(default=0, verbose_name='Email_is_out_bid')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifier', models.CharField(max_length=50, verbose_name='Notifier')),
                ('detail', models.CharField(max_length=100, verbose_name='Detail')),
                ('notification_type', models.CharField(choices=[('notification_is_replied', 'notification_is_replied'), ('notification_is_new_bid', 'notification_is_new_bid')], default='notification_is_replied', max_length=30, verbose_name='Notification Type')),
                ('notified_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
