# Generated by Django 3.2.15 on 2022-10-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='email_is_auction_end',
            field=models.BooleanField(default=1, verbose_name='Email_is_auction_end'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email_is_new_bid',
            field=models.BooleanField(default=1, verbose_name='Email_is_new_bid'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email_is_new_comment',
            field=models.BooleanField(default=1, verbose_name='Email_is_new_comment'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='email_is_out_bid',
            field=models.BooleanField(default=1, verbose_name='Email_is_out_bid'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='notification_is_new_bid',
            field=models.BooleanField(default=1, verbose_name='Notification_is_new_bid'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='notification_is_replied',
            field=models.BooleanField(default=1, verbose_name='Notification_is_replied'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='notification_is_sound',
            field=models.BooleanField(default=1, verbose_name='notifications_is_sound'),
        ),
    ]
